### LINEAR ALGEBRA TASK

##### Matrix operation

In [31]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [32]:


A=np.array([
    [2, -1],
    [0, 3],
])    
B=np.array([
    [1, 2],
    [-3, 4],
])    
print(A+B)
print(A*B)
print(3*A-2*B)

[[ 3  1]
 [-3  7]]
[[ 2 -2]
 [ 0 12]]
[[ 4 -7]
 [ 6  1]]


##### Determinant

In [30]:
import numpy.linalg as LA
LA.det(A)

np.float64(6.0)

##### Inverse

In [24]:

LA.inv(A)

array([[0.5       , 0.16666667],
       [0.        , 0.33333333]])

##### Eigenvalues and Eigenvector

In [26]:
C=np.array([
    [4,1],
    [-2,1]])

eigenvalues, eigenvectors = np.linalg.eig(C)

print("Matrix C:")
print(C)
print("Eigenvalue (first):")
print(eigenvalues[0])
print("Corresponding Eigenvector:")
print(eigenvectors[:, 0])

Matrix C:
[[ 4  1]
 [-2  1]]
Eigenvalue (first):
3.0
Corresponding Eigenvector:
[ 0.70710678 -0.70710678]


##### Car question

In [ ]:
# 4. 
# You are given a dataset of cars with the following features:Number of cylinders (x1​)Engine size in liters (x2​)Horsepower (x3)
# car 1:
# x1: 4
# x2:  1.5
# x3: 100
# and price: 20

# car 2:
# x1: 6
# x2:  2.0
# x3: 150
# and price: 30

# Then, find the price of a car 3 with features
# x1: 8
# x2:  3.0
# x3: 200
# price:?
# Hints:
# 1. Represent the given dataset as a matrix equation X.T*β=y, where X is the feature matrix, β is the coefficient vector, and y is the price vector  
# 2. Compute β (the coefficients) using the normal equation:
# β=(X.T * X)^−1  X.T y

# where,
# X.T --> transpose matrix

In [ ]:
import numpy as np
import numpy.linalg as LA

X = np.array([[4, 1.5, 100],
              [6, 2.0, 150]])
y = np.array([20, 30])

beta=np.linalg.pinv(X.T @ X) @ X.T @ y 
car3=np.array([8, 3.0, 200])
price_car3=car3 @ beta
print("Predicted price:",price_car3)



Predicted price: 39.99999999999998
